language: go
sudo: required

go:
  - 1.6

services:
    - mysql

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - pwd
    - cd ..
    - pwd 
    - baseDir="$(pwd)"
    - export GOPATH=$GOPATH:$baseDir

install:
    - go get github.com/astaxie/beego

script: 
    - go test -v -tags integration ./...