language: go
sudo: required

go:
  - 1.6

services:
    - mysql

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - Project=blog
    - mkdir $GOPATH/src/$Project
    - mv * $GOPATH/src/$Project
    - cd $GOPATH/src/$Project

install:
    - go get github.com/astaxie/beego
    - go get github.com/qiniu/api.v6
    - go get github.com/go-sql-driver/mysql

script: 
    - go build -o "$Project"  "$Project"