language: go
sudo: required

go:
  - 1.6

services:
    - mysql

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - mkdir $GOPATH/src/blog
    - mv * $GOPATH/src/blog
    - cd $GOPATH/src/blog

install:
    - go get github.com/astaxie/beego
    - go get github.com/qiniu/api.v6
    - go get github.com/go-sql-driver/mysql

script: 
    - go test -v -tags integration ./...